# Generated by Django 4.2.27 on 2025-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Featured on Homepage"
            ),
        ),
    ]
