# Generated by Django 4.2.27 on 2025-12-25
# Migration to add modeltranslation fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Location'),
        ),
    ]
