# Generated by Django 4.2.27 on 2026-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_translation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.youtube.com/watch?v=...', verbose_name='YouTube Video URL'),
        ),
    ]
