# Generated by Django 4.2.27 on 2026-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image_event_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, help_text='MP4, WebM format', null=True, upload_to='events/videos/', verbose_name='Event Video'),
        ),
    ]
