# Generated by Django 4.2.27 on 2026-04-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_description_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Meeting', 'verbose_name_plural': 'Meetings'},
        ),
    ]
