# Generated by Django 4.2.27 on 2025-12-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short description for list view",
                        max_length=300,
                        verbose_name="Excerpt",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full article content for detail view",
                        verbose_name="Content",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="Image"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("environment", "Environment"),
                            ("community", "Community"),
                            ("achievement", "Achievement"),
                            ("research", "Research"),
                            ("event", "Event"),
                        ],
                        default="environment",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "read_time",
                    models.IntegerField(default=5, verbose_name="Read Time (minutes)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Published"),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-created_at"],
            },
        ),
    ]
