# Generated by Django 4.2.27 on 2025-12-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="read_time",
        ),
    ]
