# Generated by Django 4.2.27 on 2025-12-25
# Migration to add modeltranslation fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Excerpt', help_text='Short description for list view'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='Excerpt', help_text='Short description for list view'),
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Excerpt', help_text='Short description for list view'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content', help_text='Full article content for detail view'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Content', help_text='Full article content for detail view'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Content', help_text='Full article content for detail view'),
        ),
    ]
