# Generated by Django 4.2.27 on 2026-03-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
                ('file', models.FileField(upload_to='news/media/', verbose_name='File')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'News Media',
                'verbose_name_plural': 'News Media',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news', verbose_name='News'),
        ),
    ]
