# Generated by Django 4.2.27 on 2026-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsmedia_remove_news_image_remove_news_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmedia',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Use as cover image on cards', verbose_name='Cover Image'),
        ),
    ]
