# Generated by Django 4.2.27 on 2026-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_add_uz_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='Full article content', verbose_name='Content (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(help_text='Short description for list view', max_length=300, verbose_name='Excerpt (EN)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='newsmedia',
            name='is_cover',
            field=models.BooleanField(default=False, verbose_name='Cover Image'),
        ),
    ]
