# Generated by Django 4.2.27 on 2026-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this image in the About section on homepage', verbose_name='Show on Homepage'),
        ),
    ]
