# Generated by Django 4.2.27 on 2026-03-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutimage_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='About Green Campus Initiative', max_length=100, verbose_name='Section Tag')),
                ('title', models.CharField(default='A Mission That Unites Generations', max_length=300, verbose_name='Title')),
                ('content', models.TextField(help_text='Full about text. Use paragraphs for line breaks.', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'About Content',
                'verbose_name_plural': 'About Content',
            },
        ),
    ]
