# Generated by Django 4.2.27 on 2026-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page')], default='home', max_length=5, unique=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Section Tag'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
    ]
