# Generated by Django 4.2.27 on 2026-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_page_to_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Hero Background',
                'verbose_name_plural': 'Hero Backgrounds',
                'ordering': ['order'],
            },
        ),
    ]
