# Generated by Django 4.2.27 on 2025-12-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Image"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("campus", "Campus"),
                            ("activity", "Activity"),
                            ("achievement", "Achievement"),
                            ("community", "Community"),
                        ],
                        default="event",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Featured on Homepage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
