# Generated by Django 4.2.27 on 2025-12-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="category",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="description",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="title",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="updated_at",
        ),
    ]
