# Generated by Django 4.2.27 on 2026-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Partner Name")),
                (
                    "name_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Partner Name"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Partner Name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Partner Name"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="partners/", verbose_name="Partner Logo"
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Website URL",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ["order", "name"],
            },
        ),
    ]
