# Generated by Django 4.2.27 on 2025-12-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                default="+998 00 000-00-00", max_length=20, verbose_name="Phone Number"
            ),
        ),
    ]
