# Generated by Django 4.2.27 on 2025-12-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Program Title"),
                ),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description for list view",
                        max_length=300,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        help_text="Detailed program overview", verbose_name="Overview"
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        help_text="Program goals and objectives",
                        verbose_name="Objectives",
                    ),
                ),
                (
                    "impact",
                    models.TextField(
                        blank=True,
                        help_text="Expected or achieved impact",
                        verbose_name="Impact",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="programs/",
                        verbose_name="Program Image",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Small icon for cards",
                        null=True,
                        upload_to="programs/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 6 months, Ongoing",
                        max_length=100,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "participants",
                    models.IntegerField(
                        default=0, verbose_name="Number of Participants"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "ordering": ["-created_at"],
            },
        ),
    ]
