# Generated by Django 4.2.27 on 2025-12-25
# Migration to add modeltranslation fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Program Title'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Program Title'),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Program Title'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_en',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description', help_text='Brief description for list view'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_uz',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description', help_text='Brief description for list view'),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(max_length=300, null=True, verbose_name='Short Description', help_text='Brief description for list view'),
        ),
        migrations.AddField(
            model_name='program',
            name='overview_en',
            field=models.TextField(null=True, verbose_name='Overview', help_text='Detailed program overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='overview_uz',
            field=models.TextField(null=True, verbose_name='Overview', help_text='Detailed program overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='overview_ru',
            field=models.TextField(null=True, verbose_name='Overview', help_text='Detailed program overview'),
        ),
        migrations.AddField(
            model_name='program',
            name='objectives_en',
            field=models.TextField(null=True, verbose_name='Objectives', help_text='Program goals and objectives'),
        ),
        migrations.AddField(
            model_name='program',
            name='objectives_uz',
            field=models.TextField(null=True, verbose_name='Objectives', help_text='Program goals and objectives'),
        ),
        migrations.AddField(
            model_name='program',
            name='objectives_ru',
            field=models.TextField(null=True, verbose_name='Objectives', help_text='Program goals and objectives'),
        ),
        migrations.AddField(
            model_name='program',
            name='impact_en',
            field=models.TextField(blank=True, null=True, verbose_name='Impact', help_text='Expected or achieved impact'),
        ),
        migrations.AddField(
            model_name='program',
            name='impact_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Impact', help_text='Expected or achieved impact'),
        ),
        migrations.AddField(
            model_name='program',
            name='impact_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Impact', help_text='Expected or achieved impact'),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_en',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Duration', help_text='e.g., 6 months, Ongoing'),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_uz',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Duration', help_text='e.g., 6 months, Ongoing'),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_ru',
            field=models.CharField(max_length=100, blank=True, null=True, verbose_name='Duration', help_text='e.g., 6 months, Ongoing'),
        ),
    ]
