# Generated by Django 5.2.10 on 2026-01-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0004_remove_translation_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="icon",
        ),
    ]
