# Generated by Django 4.2.27 on 2026-03-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_remove_icon_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='image',
        ),
        migrations.CreateModel(
            name='ProgramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5, verbose_name='Type')),
                ('file', models.FileField(upload_to='programs/media/', verbose_name='File')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='programs.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Media',
                'verbose_name_plural': 'Program Media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
