# Generated by Django 4.2.27 on 2026-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_remove_program_image_programmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmedia',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Use as cover image on cards', verbose_name='Cover Image'),
        ),
    ]
